export const IMAGES = {
  pageOneBg: require('./kids.png'),
  title: require('./title.png'),
  illustration0: require('./onBoarding2.png'),
  illustration1: require('./artwork.png'),
  illustration2: require('./onboarding4.png'),
  illustration3: require('./onboarding7.png'),
  illustration4: require('./onboarding5.png'),
  illustration5: require('./welcome.png'),
  signupBackground: require('./signupBackground.png'),
  appleIcon: require('./appleIcon.png'),
  googleIcon: require('./googleIcon.png'),
  emailIcon: require('./emailIcon.png'),
  edit: require('./editIcon3x.png'),
  trash: require('./trash3x.png'),
  movefolder: require('./movefolder3x.png'),
  close: require('./x.png'),
  folder: require('./folder.png'),
  addFolder: require('./addFolder.png'),
  rectangle1: require('./rectangle1.png'),
  rectangle2: require('./rectangle3.png'),
  rectangle3: require('./rectangle2.png'),
  rectangle4: require('./videoicon.png'),
  rectangle5: require('./sidearrow.png'),
  rectangle6: require('./version.png')
}